name: Deploy Extension

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  # Step 1: Pack Extension for Chromium
  packChromium:
    runs-on: ubuntu-latest
    outputs:
      zip_path: ${{ steps.pack.outputs.zipFilePath }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Extension
        id: pack
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: '.'
          zipFilePath: 'build/extension-chromium.zip'

      - name: Upload Packed Extension
        uses: actions/upload-artifact@v4
        with:
          name: extension-chromium
          path: build/extension-chromium.zip

  # Step 1.1.1: Fetch Google Access Token
  fetchGToken:
    runs-on: ubuntu-latest
    needs: packChromium
    outputs:
      access_token_path: google-access-token
    steps:
      - id: fetchToken
        uses: cardinalby/google-api-fetch-token-action@v1
        with:
          clientId: ${{ secrets.G_CLIENT_ID }}
          clientSecret: ${{ secrets.G_CLIENT_SECRET }}
          refreshToken: ${{ secrets.G_REFRESH_TOKEN }}

      - name: Save access token
        run: |
          echo "${{ steps.fetchToken.outputs.accessToken }}" > access_token.txt
    
      - name: Upload token as artifact
        uses: actions/upload-artifact@v4
        with:
          name: google-access-token
          path: access_token.txt

  # Step 1.1.2: Upload Extension to the Chrome Web Store
  uploadGoogle:
    runs-on: ubuntu-latest
    needs: [packChromium, fetchGToken]
    steps:
      - name: Download token artifact
        uses: actions/download-artifact@v4
        with:
          name: google-access-token

      - name: Download extension artifact
        uses: actions/download-artifact@v4
        with:
          name: extension-chromium

      - name: Read access token
        id: read-token
        run: echo "ACCESS_TOKEN=$(cat access_token.txt)" >> $GITHUB_ENV

      - name: Upload to Chrome Web Store
        uses: cardinalby/webext-buildtools-chrome-webstore-action@v1
        with:
          zipFilePath: 'extension-chromium.zip'
          extensionId: 'pdbjikelneighjgjojikkmhiehpcokjm'
          apiAccessToken: ${{ env.ACCESS_TOKEN }}

  # Step 1.1.3: Publish Extension to the Chrome Web Store
  publishGoogle:
    runs-on: ubuntu-latest
    needs: uploadGoogle
    steps:
      - name: Download token artifact
        uses: actions/download-artifact@v4
        with:
          name: google-access-token

      - name: Read access token
        id: read-token
        run: echo "ACCESS_TOKEN=$(cat access_token.txt)" >> $GITHUB_ENV

      - name: Publish to Chrome Web Store
        uses: cardinalby/webext-buildtools-chrome-webstore-publish-action@v1
        with:
          extensionId: 'pdbjikelneighjgjojikkmhiehpcokjm'
          apiAccessToken: ${{ env.ACCESS_TOKEN }}
  
  # Step 1.2.1: Upload and Publish to the Microsoft Edge Add-ons
  uploadAndPublishEdge:
    runs-on: ubuntu-latest
    needs: packChromium
    steps:
      - name: Download extension artifact
        uses: actions/download-artifact@v4
        with:
          name: extension-chromium
      
      - name: Publish to Microsoft Edge Add-ons
        uses: wdzeng/edge-addon@v2
        with:
          zip-path: 'extension-chromium.zip'
          product-id: 'fc9fbef4-2a2a-41e4-8b2e-5dc5986cad74'
          api-key: ${{ secrets.EDGE_API_KEY }}
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
